namespace EagerRegistry;

internal static class Constants
{
	public const string DefaultServiceLifetime = "Transient";
	public const string Namespace = "EagerRegistry";
	public const string GlobalScope = "global";
	public const string EnumsNamespace = "EagerRegistry.Enums";
	public const string Header = $$"""
	                               //------------------------------------------------------------------------------
	                               // <auto-generated>
	                               //     This code was generated by the {{nameof(EagerRegistry)}} source generator.
	                               //
	                               //     Changes to this file may cause incorrect behavior and will be lost if
	                               //     the code is regenerated.
	                               // </auto-generated>
	                               //------------------------------------------------------------------------------
	                               """;
}