using System.Threading;
using EagerRegistry.Utils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EagerRegistry.Generator;

internal sealed partial class EagerRegistryGenerator
{
	private static bool Filter(SyntaxNode node, CancellationToken _)
	{
		return node is ClassDeclarationSyntax theClass
		       && theClass.IsNotAutoGenerated()
		       && theClass.IsNotStaticOrAbstract()
		       && theClass.IsNotNested()
		       && theClass.HasPublicNonStaticMethodsOrProperties();
	}
}
